---
apiVersion: services.cloud.sap.com/v1
kind: ServiceBinding
metadata:
  name: jakarta-ams-identity-binding
  labels:
    app: jakarta-ams-sample
spec:
  serviceInstanceName: jakarta-ams-identity
  credentialsRotationPolicy:
    enabled: true
    rotationFrequency: 672h # rotate every 28 days
    rotatedBindingTTL: 336h # keep old binding for another 14 days
  parameters:
    credential-type: "X509_GENERATED"
    app-identifier: "jakarta-ams-sample"
