apiVersion: v1
kind: Config
clusters:
  - name: default-cluster
    cluster:
      server: https://api.$K8S_API_SERVER_URL
      certificate-authority-data: $K8S_SERVER_CERT
users:
  - name: default-user
    user:
      token: $K8S_DEPLOY_TOKEN
contexts:
  - name: $K8S_API_SERVER_URL
    context:
      cluster: default-cluster
      namespace: $K8SNAMESPACE
      user: default-user
current-context: $K8S_API_SERVER_URL