//SPDX-FileCopyrightText: 2020
//SPDX-License-Identifier: Apache-2.0

@startuml
skinparam Monochrome true
hide footbox

actor        AppDeveloper as user
participant  "kubectl plugin" as kubctlplugin
participant  "Authorization Sidecar (incl. OPA)" as pdp
participant  "Bundle Gateway" as gw
database     "Policies & User Assignments" as db
participant  "Authorization Management Service\n(AMS)" as ams


user -> kubctlplugin: kubctl dcl upload
activate kubctlplugin
kubctlplugin -> ams: upload base policies
activate ams
ams -> db
deactivate ams
deactivate kubctlplugin

loop every 60 seconds
    pdp -> gw: fetch bundle if modified
    gw  -> db
    pdp -> pdp: update policy engine

end
@enduml

