@startuml
skinparam Monochrome true
hide footbox

"JUnit (MVC)" -> "Request Post Processor" : userWithPolicies()
"Request Post Processor" -> "Authorization Decision Controller (ADC)" : collect potential authorities POST ADC_URL/v1/data/rbac/compile (ignores conditions)
"Request Post Processor" -> "Spring Security (+ams)" : enrich authorities (SecurityContext)
"Request Post Processor" -> "Spring Security (+ams)" : enrich claim / attributes with "test_policies" (SecurityContext)
"JUnit (MVC)" -> Application: /readByCountry/{country}
Application -> "Spring Security (+ams)" : access("hasBaseAuthority('read', 'salesOrders')")
"Spring Security (+ams)" -> "Spring Security (+ams)" : has potential authority (SecurityContext)
Application -> "Spring Security (+ams)" : @PreAuthorize("forAction('read', 'CountryCode="'+#country+'\"')")
"Spring Security (+ams)" -> "Authorization Decision Controller (ADC)" : POST ADC_URL/v1/data/rbac/allow (with policies)
@enduml


