---
### PVC for DCL files
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dcl-files-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
---
###  SERVICE INSTANCE CONFIGURATION  ###
# Identity instance
apiVersion: services.cloud.sap.com/v1
kind: ServiceInstance
metadata:
  name: auth
spec:
  serviceOfferingName: identity
  servicePlanName: application
  parameters:
    authorization:
      product_label: "IAS-AMS Spring example app (Kyma)"

---
apiVersion: services.cloud.sap.com/v1
kind: ServiceBinding
metadata:
  name: identity-service-binding
spec:
  serviceInstanceName: auth
  credentialsRotationPolicy:
    enabled: true
    rotationFrequency: 672h # rotate every 28 days
    rotatedBindingTTL: 336h # keep old binding for another 14 days
  parameters:
    credential-type: "X509_GENERATED"
    app-identifier: "ams-sample-app"
---
###  APPLICATION CONFIGURATION  ###
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ams-sample-app
  name: ams-sample-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ams-sample-app
  strategy: {}
  template:
    metadata:
      labels:
        app: ams-sample-app
    spec:
      imagePullSecrets:
        - name: <YOUR IMAGE PULL SECRET>
      initContainers:
        - name: copy-dcl-files
          image: <YOUR IMAGE REPOSITORY>
          command: [ 'sh', '-c', 'cp -R /dcl-data/* /dcl-files/' ]
          volumeMounts:
            - name: dcl-files
              mountPath: "/dcl-files"
            - name: auth-secret
              mountPath: "/bindings/identity"
              readOnly: true
      containers:
        - image: <YOUR IMAGE REPOSITORY>
          imagePullPolicy: Always
          name: backend
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - name: auth-secret
              mountPath: "/bindings/identity"
              readOnly: true
            - name: dcl-files
              mountPath: "/dcl-files"
          env:
            - name: SERVICE_BINDING_ROOT
              value: "/bindings"
        - image: cloud-security-integration.common.repositories.cloud.sap/ams-k8s-sidecar:0.53.1-sap-0.3.3-1
          imagePullPolicy: Always
          securityContext:
            runAsNonRoot: true
            runAsUser: 443
          name: adc-sidecar
          ports:
            - name: sidecar
              containerPort: 8181
              protocol: TCP
          volumeMounts:
            - name: auth-secret
              mountPath: "etc/secrets/sapbtp/identity/auth"
              readOnly: true
        - image: <YOUR APPROUTER IMAGE REPOSITORY>
          imagePullPolicy: Always
          name: approuter
          ports:
            - name: http
              containerPort: 5000
          volumeMounts:
            - name: auth-secret
              mountPath: "etc/secrets/sapbtp/identity/auth"
              readOnly: true
          env:
            - name: destinations
              value: |-
                [{
                    "name": "ams-spring-app-destination",
                    "url": "http://localhost:8080",
                    "forwardAuthToken": true
                }]
      volumes:
        - name: dcl-files
          persistentVolumeClaim:
            claimName: dcl-files-pvc
        - name: auth-secret
          secret:
            secretName: identity-service-binding
---
### DCL Upload Job
apiVersion: batch/v1
kind: Job
metadata:
  name: dcl-upload-job
spec:
  ttlSecondsAfterFinished: 150
  template:
    spec:
      imagePullSecrets:
        - name: sap-repo-registry
      containers:
        - name: upload-container
          imagePullPolicy: Always
          image: cloud-security-integration.common.repositories.cloud.sap/dcl-uploader:0.0.2
          env:
            - name: AMS_LOG_LEVEL
              value: debug
          volumeMounts:
            - name: dcl-files
              mountPath: /dcl-files
            - name: auth-secret
              mountPath: /bindings/identity
              readOnly: true
      volumes:
        - name: dcl-files
          persistentVolumeClaim:
            claimName: dcl-files-pvc
        - name: auth-secret
          secret:
            secretName: identity-service-binding
      restartPolicy: OnFailure
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ams-sample-app
  name: ams-sample-app
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: ams-sample-app # refer to pods with label = app: ams-sample-app

---
apiVersion: gateway.kyma-project.io/v1beta1
kind: APIRule
metadata:
  name: ams-sample-app-api
  labels:
    app: ams-sample-app
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  host: ams-sample-app-api
  rules:
    - accessStrategies:
        - config: {}
          handler: allow
      methods: ["GET", "POST"]
      path: /.*
  service:
    name: ams-sample-app
    port: 80
