---
apiVersion: v1
kind: Service
metadata:
  name: spring-security-ams-service
  labels:
    app: spring-security-ams
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 5000
  selector:
    app: spring-security-ams # refer to pods with label = app: spring-security-ams